<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><getBusinessProcessTokenResponse xmlns="http://internal.mathworks.com/businessprocesstokenws/services"><getBusinessProcessTokenReturn><token>TestTokenValue</token><result>0</result></getBusinessProcessTokenReturn></getBusinessProcessTokenResponse></soapenv:Body></soapenv:Envelope>


